### ISSUE TITLE
Add ServiceMonitors for bookinfo and emojivoto to scrape linkerd proxy

### ISSUE THREAD

**Issue by surajssd** [kinvolk/service-mesh-benchmark#22]
Add servicemonitors to srape metrics of the linkerd proxy running on port 4191. Similar to https://github.com/kinvolk/lokomotive/pull/690.

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: <emojivoto|bookinfo>
    release: prometheus-operator
  name: linkerd-proxies
  namespace: {{.Release.Namespace}}
spec:
  selector:
    matchLabels:
      <app-label>
  endpoints:
  - targetPort: 4191
```
